In [1]:
import pandas as pd

PANDAS SERIES

In [3]:
paises = pd.Series(['Perú','Chile','Colombia','Ecuador'],index=[1,7,10,30])
paises

1         Perú
7        Chile
10    Colombia
30     Ecuador
dtype: object

In [4]:
paises = pd.Series(['Perú','Chile','Colombia','Ecuador'])
paises

0        Perú
1       Chile
2    Colombia
3     Ecuador
dtype: object

In [5]:
dict = {1:'Perú',7:'Chile',10:'Colombia',30:'Ecuador'}
pd.Series(dict)

1         Perú
7        Chile
10    Colombia
30     Ecuador
dtype: object

In [6]:
paises[0:3]

0        Perú
1       Chile
2    Colombia
dtype: object

DATAFRAME

In [8]:
dict = {'paises':['Perú','Chile','Colombia','Ecuador'],
      'pbi':[183.0,170.0,170.0,165.0],
      'habitantes':[33,20,20,10]
      }

df_paises = pd.DataFrame(dict)
df_paises

     paises    pbi  habitantes
0      Perú  183.0          33
1     Chile  170.0          20
2  Colombia  170.0          20
3   Ecuador  165.0          10

In [10]:
df_paises.columns

Index(['paises', 'pbi', 'habitantes'], dtype='object')

In [11]:
df_paises.index

RangeIndex(start=0, stop=4, step=1)

In [12]:
df_paises.describe()

              pbi  habitantes
count    4.000000    4.000000
mean   172.000000   20.750000
std      7.702813    9.429563
min    165.000000   10.000000
25%    168.750000   17.500000
50%    170.000000   20.000000
75%    173.250000   23.250000
max    183.000000   33.000000